project:
  type: website

website:
  title: "Life Expectancy Logistic Regression"
  navbar:
    left:
      - href: background.qmd
        text: Background
      - href: log_reg.qmd
        text: Logistic Regression

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

